### ISSUE TITLE
alt removing drops

### ISSUE THREAD

**Issue by GG-MD** [Dreeam-qwq/Leaf#310]
### Checklist

- [x] I have searched the existing issues and the documentation
- [ ] I ticked all the boxes without actually reading them
- [x] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [x] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

```
    alt-item-despawn-rate:
      enabled: true
      items:
        andesite: 300
        arrow: 120
        basalt: 300
        blackstone: 300
        bone: 300
```
It was always in seconds, i.e. 300 = should be 5 minutes, but items are removed after 5 sec. eventually....

### What is the expected behavior?

-

### How to reproduce?

-

### Spark profiler link

-
